### ISSUE TITLE
Negativbeträge

### ISSUE THREAD

**Issue by kmein** [flipdot/drinks-scanner-display#11]
Wie es aussieht, kann man negativbeträge aufladen, obwohl der code das verhindern sollte.
Die stelle ist [`webserver.py` (Z. 53f.)](https://github.com/flipdot/drinks-scanner-display/blob/master/webserver/webserver.py). 

![Screenshot](https://i.imgur.com/e0mbudd.png)

**Comment by cfstras** [comment]
ich kapier grad nicht warum der code das zulässt, aber das ist durchaus gewollt. z.b für „überweisungen“. a lädt sich - 5 auf, b lädt + 5.

**Comment by malled2002** [comment]
> ich kapier grad nicht warum der code das zulässt
amount ist an der Stelle ne Zeichenkette.
