### ISSUE TITLE
Freibier für zahlende Member

### ISSUE THREAD

**Issue by cfstras** [flipdot/drinks-scanner-display#15]
Pro Monat, sobald Geldeingang am Konto

Diskussion? Ja/nein?

**Comment by soerface** [comment]
https://www.buhl.de/meinverein/wann-ist-der-mitgliedsbeitrag-eine-spende-unterschiede/

> Der Vorstand sollte sehr genau darauf achten, dass Spenden, die als solche behandelt werden sollen, wirklich keine Gegenleistungen verlangen.

> Spenden dürfen grundsätzlich mit keinen Gegenleistungen verbunden sein.

daher :-1:

**Comment by cfstras** [comment]
Hmmm.... so wie ich diesen Artikel gerade verstehe, dürften wir generell Mitgliedsbeiträge nicht absetzen. Dürfen wir aber. Also fehlt da irgendwas. Meinst du, dass dieses Ticket das angreift?

**Comment by soerface** [comment]
> Eine Ausnahme bilden Beiträge an gemeinnützige Körperschaften, deren Zweck als besonders förderungswürdig im Sinne des Spendenrechtes gilt.

Ka ob das durch sowas torpediert wird

**Comment by cfstras** [comment]
hm... Und "darf Tür öffnen" etc sind keine "Gegenleistungen"? Klingt nach "wir brauchen einen Anwalt" :D

**Comment by soerface** [comment]
Würde behaupten, dass Zugang zu den Räumen Teil unseres förderberechtigten Zweckes ist, sprich Förderung von Bildung / Bereitstellung von Werkzeugen, damit sich Menschen weiterbilden können. Also etwas, wo der Staat sagt „Jo das ist cool, brauchst keine Steuern dafür bezahlen, dass du dafür jeden Monat Geld ausgibst“. Bei Bier trinken kann ich mir nicht vorstellen, dass der Staat das steuerlich fördern will.

Aber ja, IANAL

**Comment by cfstras** [comment]
#20
