### ISSUE TITLE
Geldbeträge: immer als decimal speichern. (war: Anzahl Nachkommastellen begrenzen)

### ISSUE THREAD

**Issue by jplatte** [flipdot/drinks-scanner-display#22]
Siehe mein Account. Wäre sinnvoll, immer zwei oder keine Nachkommastellen anzuzeigen. Oder am besten gleich Sub-Cent-Beträge im gesamten Backend verbieten ;)

**Comment by Dargmuesli** [comment]
Außerdem bitte dabei noch gleich den "+/-"-Prefix abschaffen. Die Sparkassen-App mag QR-Code-Werte für `amount` von `+5` nicht (`5` geht).

**Comment by jplatte** [comment]
Inzwischen scheinen bei meinem Account nur noch 4 (oder 5? kann heute abend nachgucken) Nachkommastellen angezeigt zu werden. Sinnvoll wären aber natürlich 2.
